### ISSUE TITLE
No Authorization header in request

### ISSUE THREAD

**Issue by whity-art** [compwright/axios-oauth-client#9]
Hi,

I tried to login to OAuth based server, and there is no problem, if I use Postman. 

My applications base on React, Redux-Saga. 

My login function looks like this:

```

const oauthParams = {
    url: ApiUrl.LOG_IN,
    grant_type: 'password',
    client_id: 'properclient',
    client_secret: 'properpass',
    username: '',
    password: '',
    response_type: 'token',
    scope: 'any'
}

export function* logIn(action) {
    const {
        payload: { name, password }
    } = action
    oauthParams.username = name
    oauthParams.password = password

    try {
        const oauthResponse = yield call(API.post, ApiUrl.LOG_IN)
    } catch (e) {
    }
}
```

My interceptor:

```
import axios from 'axios'
import oauth from 'axios-oauth-client'
import tokenProvider from 'axios-token-interceptor'
import { oauthParams } from '../redux/sagas'

const getOwnerCredentials = () => oauth.client(axios.create(), oauthParams)()

const axiosInstance = axios.create()
axiosInstance.interceptors.request.use(
    oauth.interceptor(tokenProvider, getOwnerCredentials)
)
```

But unfortunately I receive from server 401 - unauthorized.  

```
Request:

Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9
Connection: keep-alive
Content-Length: 126
Content-Type: application/x-www-form-urlencoded
Host: somehost
Origin: http://localhost:3002
Referer: http://localhost:3002/login
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
```

```
Form data:

grant_type: password
client_id: properclient
client_secret: properpass
username: user
password: pass
response_type: token
scope: any
```

For sure I used the same data for Postman and I received token. The only difference it Authorization header which I dont have in my requests. 

![auth](https://user-images.githubusercontent.com/60513204/73548196-42ee6b00-4438-11ea-8a1b-0c82db4a78db.JPG)

Any advice? I will be grateful for your help.

**Comment by anentropic** [comment]
I have the same problem... some hosts require the client id and secret to be sent as basic auth header rather than in the body

I'm working with one right now where even if I update the axios instance I'm passing to this lib to have the basic auth applied it still fails - they don't like having those values in the body apparently, even if it also has the header they do want 😢

**Comment by compwright** [comment]
Hi @anentropic, this library is just a shortcut library to cut out some of the boilerplate. It's perfectly acceptable to make a direct axios call to your token endpoint without this library. If you wish to add support for sending in the header rather than the body, I'd be glad to have a PR to add that feature. Currently, however, it is not supported.
